config/routes.rb
Rails.application.routes.draw do
	resources :posts do
  		resources :comments
        member do
        get 'like'
      end
      
	end
  	devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: 'registrations'
      }
	root to: 'posts#index' 
	get "/:username", to: "users#show", as: "user_show"
	as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

before_action :set_post

	def create
  		@comment = @post.comments.build(comment_params)
  		@comment.user_id = current_user.id

      

  		if @comment.save
    		redirect_to post_path(@post)
  		else
    		render root_path
  		end
	end

	def destroy
  		@comment = @post.comments.find(params[:id])
  		@comment.destroy
  		flash[:success] = "Comment deleted :("
  		redirect_to (@post)
	end

	private

	def comment_params
  		params.require(:comment).permit(:content)
	end

	def set_post
  		@post = Post.find(params[:post_id])
	end

end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
					
<div class="user-name">
	<%= comment.user.username %>:
</div>
<div class="comment-content">
	<%= comment.content %>
<% if comment.user == current_user %>
  	<%= link_to post_comment_path(post, comment), method: :delete, data: { confirm: "Are you sure?" }, remote: true do %>
    	<span class="glyphicon glyphicon-remove delete-comment"> </span>
  						<% end %>
					<% end %>	
</div>
<br>

app/views/comments/create.js.erb
$('#comments_<%= @post.id %>').append("<%=j render 'comments/comment', post: @post, comment: @comment %>");
$('#comment_content_<%= @post.id %>').val('')