config/routes.rb
Rails.application.routes.draw do
	resources :posts do
  		resources :comments
        member do
        get 'like'
      end
      
	end
  	devise_for :users, controllers: {
        sessions: 'users/sessions', registrations: 'registrations'
      }
	root to: 'posts#index' 
	get "/:username", to: "users#show", as: "user_show"
	as :user do
  get 'users', :to => 'users#show', :as => :user_root # Rails 3
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.erb
<nav class="navbar justify-content-between">
  <a class="navbar-brand" href="#">PromptoSNAP!</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <form class="form-inline">
        <a class="nav-item" href="/">Home</a>
     
     <!-- views/devise/menu/_login_items.html.erb -->
  <% if user_signed_in? %>
 
  <a class="nav-item">
  <%= link_to('New Post', new_post_path, {class: 'nav-link'}) %>        
  </a>
  <a class="nav-item">
  <%= link_to('Logout', destroy_user_session_path, {method: :delete, class: 'nav-link'}) %>        
  </a>
  <a class="nav-item">
  <%= link_to('Settings', edit_user_registration_path, {class: 'nav-link'}) %>        
  </a>
  
<% else %>
  <a class="nav-item">
  <%= link_to('Login', new_user_session_path, {class: 'nav-link'}) %>  
  </a>
  <a class="nav-item">
  <%= link_to('Sign-up', new_user_registration_path, {class: 'nav-link'}) %>  
  </a>
<% end %>

</form>
  <form class="form-inline">
    <% if user_signed_in? %>

  <a class="round-image-25"><%= image_tag(current_user.avatar.url(:thumb)) %></a>
        <a class="nav-item">
            <%= link_to(current_user.username, user_show_path(current_user.username), {class: 'nav-link'}) %>  
                  </a>
    <%  end %>
  </form>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromptoSNAP</title>
      <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body>
<%= render :partial => 'layouts/navbar' %>
    <%= yield %>

           <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
  </body>
</html>